version: "3"
services:
    backapi:
        image: "{{image}}:{{commit}}"
        hostname: "{{service}}"
        labels:
            com.docker.stack.namespace: "{{service}}"
        networks:
            - compliance
        deploy:
            placement:
              constraints:
                - node.labels.network == private
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 3s
networks:
    compliance:
        external:
            name: compliance
