#!groovy?

import com.cloudbees.groovy.cps.NonCPS
import groovy.json.JsonSlurper

def createGithubPullRequest(String message, String project, String branch, String username, String token) {
    try {

        def body = """
        {
          "title": "${message}",
          "head": "${branch}",
          "base": "master"
        }
        """
        echo "sending body: ${body}\n"
        def response = httpRequest acceptType: 'APPLICATION_JSON', contentType: 'APPLICATION_JSON', httpMode: 'POST', requestBody: body, customHeaders: [[name: "Authorization", value: "Bearer ${token}"]], url: "https://api.github.com/repos/${project}/pulls"

        echo "responce status: ${response}"
        return response

    } catch (err) {
        error "ERROR  ${err}"
    }
}

def createBitbucketPullRequest(url, text) {
  def payload = JsonOutput.toJson(text) 
    sh "curl -n -X POST -H 'Content-Type: application/json' --data ${payload} ${url}"
}

pipeline {

  agent {label 'slave'}
  environment{
    GIT_REPO='github.com/ironSource/ci-cd-from-scratch-webserver.git'
  }
  stages {
    stage ('PREBUILD') {

      steps {
        step([$class: 'WsCleanup'])
      }
    }
    stage ('CHECKOUT') {
      steps {
        git branch: 'staging', credentialsId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', url: "https://${env.GIT_REPO}"
      }
    }
    stage ('SET ENVIRONMENT VARIABLES') {
      steps {
        withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD']]) {
          sh '''
            set +e
            set +x
            echo env.GIT_USERNAME=${GIT_USERNAME} > env.properties
            echo env.GIT_PASSWORD=${GIT_PASSWORD} >> env.properties
            echo env.GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD) >> env.properties
            echo env.ORIGINAL_BRANCH=$(git rev-parse --abbrev-ref HEAD) >> env.properties
            echo env.GIT_COMMIT=$(git rev-parse HEAD) >> env.properties
            cat env.properties
          '''
        }

        sh '''
          sed 's/$/"/g' -i env.properties
          sed 's/=/="/g' -i env.properties
        '''

        sh 'cat infra/jenkins-env-variables.groovy >> env.properties'

        load ('env.properties')
      }
    }

    stage ('VALIDATE BRANCH') {
      when {
        expression {
          return !(env.GIT_BRANCH =~ /^(feature|test|bug|staging|master)/)
        }
      }
      steps {
        echo env.GIT_BRANCH 
        echo 'branch is not supported'
        sh 'exit 1'
      }
    }
    stage ('MERGE TO STAGING') {
      when {
        expression {return env.GIT_BRANCH =~ /^(feature|test|bug)/}
      }
      steps {
        sh '''
          git config user.name '<%your username%>'
          git config user.email '<%your email%>'
          git checkout staging
          git merge ${GIT_BRANCH}
          echo env.GIT_COMMIT=$(git rev-parse HEAD) > merge.properties
          echo env.GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD) >> merge.properties
          sed 's/$/"/g' -i merge.properties
          sed 's/=/="/g' -i merge.properties
        '''
        load ('merge.properties')
      }
    }

    stage ('BUILDING IMAGE') {
      steps {
        ansiblePlaybook(
          extras: '-c local -v',
          playbook: 'infra/build-playbook.yml',
          extraVars: [
            commit: env.GIT_COMMIT,
            image: env.DOCKER_REPO,
            branch: env.GIT_BRANCH
          ])
      }
    }
    stage ('RUN UNIT TESTS') {
      steps {
        ansiblePlaybook(
          extras: '-c local -v',
          playbook: 'infra/unit-test-playbook.yml',
          extraVars: [
            commit: env.GIT_COMMIT,
            image: env.DOCKER_REPO,
            name: env.COMPONENT
          ])
      }
    }
    stage ('PUSH IMAGE TO REGISTRY') {
      steps {
        ansiblePlaybook(
          extras: '-c local -v',
          playbook: 'infra/push-to-docker-hub-playbook.yml',
          extraVars: [
            commit: env.GIT_COMMIT,
            image: env.DOCKER_REPO,
            branch: env.GIT_BRANCH
        ])
      }
    }

    stage ('PUSH TO REMOTE STAGING BRANCH') {
      when {
        expression {return env.ORIGINAL_BRANCH=~ /^(feature|test|bug)/}
      }
      steps {
        withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD']]) {
          sh '''
            git push https://${GIT_USERNAME}:${GIT_PASSWORD}@${GIT_REPO}
          '''
        }
      }
    }

    stage ('DEPLOY') {
      steps {
        ansiblePlaybook(
          playbook: 'infra/deploy-playbook.yml',
          inventory: 'infra/inventory.ini',
          extras: '-v',
          extraVars: [
            commit: env.GIT_COMMIT,
            image:  env.DOCKER_REPO,
            service: env.COMPONENT,
            environment: env.GIT_BRANCH,
            branch: env.GIT_BRANCH])
      }
    }
    stage ('CREATE PULL REQUEST') {
      when {
        expression {return env.GIT_BRANCH == 'staging'}
      }
      steps {
        withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_TOKEN']]) {
          createGithubPullRequest("tests jenkins pull request", env.PROJECT, env.GIT_BRANCH, env.GIT_USERNAME, env.GIT_TOKEN)
        }
      }
    }
  }
}

